### ISSUE TITLE
TA-dmarc fails to install

### ISSUE THREAD

**Issue by ekzp** [aholzel/TA-dmarc#1]
Environment: Single instance Splunk Enterprise 7.2.1 Free License, running on Windows Server 2016 Standard 64-bit.

Issue: TA-dmarc-master fails to install. The add-on does not appear in the Splunk App Manager's app list.

Found the following in splunkd.log:

```
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':  Traceback (most recent call last):
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\bin\runScript.py", line 78, in <module>
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':      execfile(REAL_SCRIPT_NAME)
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\etc\apps\TA-dmarc-master\bin\setup_handler.py", line 36, in <module>
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':      import classes.custom_logger as c_logger
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\etc\apps\TA-dmarc-master\bin\classes\custom_logger.py", line 39, in <module>
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':      splunk_info = si.Splunk_Info(sessionKey="NA")
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\etc\apps\TA-dmarc-master\bin\classes\splunk_info.py", line 54, in __init__
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':      log_level = self.get_config(custom_conf_file, 'main', 'log_level')
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\etc\apps\TA-dmarc-master\bin\classes\splunk_info.py", line 188, in get_config
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':      if int(active_config) > 0 and int(active_config) < 20:
01-25-2019 19:38:32.006 +1100 ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\PYTHON.EXE C:\Program Files\Splunk\bin\runScript.py setup':  TypeError: int() argument must be a string or a number, not 'NoneType'
01-25-2019 19:38:32.025 +1100 ERROR AdminManagerExternal - External handler failed with code '1' and output: ''.  See splunkd.log for stderr output.
01-25-2019 19:38:32.025 +1100 ERROR SetupAdminHandler - Error while fetching url=/servicesNS/nobody/TA-dmarc-master/ta-dmarc/ta-dmarc_configure/main/?_strict=true;search=%20eai%3Aacl.app%3D%22%22%20OR%20eai%3Aacl.app%3D%22TA-dmarc-master%22

```
Please advise how to make it install.

Thanks,
Zoltan

**Comment by aholzel** [comment]
Sorry for the late response.

Based on the error I whould say that the app is installed. If you don't see it in the navigation menu that is because of the setting in [app.conf](https://github.com/aholzel/TA-dmarc/blob/master/default/app.conf) under the [ui] stanza if you change 
`show_in_nav = false`  to  `show_in_nav = true`
you should see the app.

I didn't test it on a Windows 2016 machine but I did test it (and got it working) on a Windows 2012R2 system.

**Comment by ekzp** [comment]
Hi Arnold,

Thank you for the response.

Here is what I do:

1. I go to Apps -> Manage Apps
2. In the TA-dmarc line I click "Set Up":

[image: image.png]
[looks like screenshots]

3. I end up with this:

[image: image.png] - this would show a 500 - Internal server error.
If I click the "View more information..." link, I get an empty list:

[image: image.png] - It's an empty list with no reason as to what the error is.

What do you recommend trying?

Thanks,
Zoltan

**Comment by aholzel** [comment]
I am sorry but I don't see any screenshots I only see 

`[image: image.png]`

**Comment by ekzp** [comment]
Hi Arnold,

I saw that the portal removed the images and replaced them with
placeholders.

I added some descriptive comments, trying to make up for the missing images.

How else can I upload screenshots?

Thanks,
Zoltan
