### ISSUE TITLE
Unable to setup, python error in splunk

### ISSUE THREAD

**Issue by lazyfai** [aholzel/TA-dmarc#2]
Splunk version 7.2.6
Install TA-dmarc version 3.5.1
Once click on setup, it shows error page, and in splunk web_service.log:
2019-04-21 21:44:22,920 INFO    [5cbc73b68b7f8f087dbe50] error:323 - GET /en-US/manager/TA-dmarc-3.5.1/apps/local/TA-dmarc-3.5.1/setup 127.0.0.1 8065
2019-04-21 21:44:22,920 INFO    [5cbc73b68b7f8f087dbe50] error:324 - 500 Internal Server Error The server encountered an unexpected condition which prevented it from fulfilling the request.
2019-04-21 21:44:22,921 ERROR   [5cbc73b68b7f8f087dbe50] error:325 - Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 606, in respond
    cherrypy.response.body = self.handler()
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/htmlinjectiontoolfactory.py", line 72, in wrapper
    resp = handler(*args, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/routes.py", line 366, in default
    return route.target(self, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 38, in rundecs
    return fn(*a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 119, in check
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 167, in validate_ip
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 335, in preform_sso_check
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 374, in check_login
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 394, in handle_exceptions
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/decorators.py", line 449, in apply_cache_headers
    response = fn(self, *a, **kw)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/controllers/admin.py", line 1715, in listEntities
    app_name = eai_acl.get('app')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by geekusa** [comment]
I had this problem too. I downloaded the repo as a zip and unpacked it. The top level folder was called "TA-dmarc-master", by renaming the folder to "TA-dmarc" the setup page then worked without error.

**Comment by DBorGe** [comment]
I've tried your solution @geekusa but either way, it doesn't work. I've tried the last TA-addon version with splunk 8.0.5 and 7.2.6 and nothing. @lazyfai did you managed to make it work?

@aholzel can you help me here?

`2020-08-20 09:19:23,237 ERROR	[5f3e320a2020f4f094860] error:325 - Traceback (most recent call last):
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\cherrypy\_cprequest.py", line 606, in respond
    cherrypy.response.body = self.handler()
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\htmlinjectiontoolfactory.py", line 72, in wrapper
    resp = handler(*args, **kwargs)
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\cherrypy\_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\routes.py", line 366, in default
    return route.target(self, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 38, in rundecs
    return fn(*a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 119, in check
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 167, in validate_ip
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 335, in preform_sso_check
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 374, in check_login
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 394, in handle_exceptions
    return fn(self, *a, **kw)
  File "&lt;string&gt;", line 1, in &lt;lambda&gt;
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 449, in apply_cache_headers
    response = fn(self, *a, **kw)
  File "C:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\appserver\mrsparkle\controllers\admin.py", line 1715, in listEntities
    app_name = eai_acl.get('app')
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by aholzel** [comment]
@DBorGe 
I think it is a problem with the windows python version. In theory it should have the same options as the linux version but hey that is the theory..... 
what windows version are you using, many I can spin up a system and check to see if I can reproduce your problems.
