### ISSUE TITLE
TA-dmarc installation issue

### ISSUE THREAD

**Issue by tonyjoseph-sfo** [aholzel/TA-dmarc#7]
Hi, i am unable to start the setup.
running the latest version of splunk on windows 10.
App is not visible in apps. If i open the manage apps i can see TA-DMARC, clicking on setup throws "500 Internal Server Error"

the url also looks incorrect to me https://10.4.100.1/en-GB/manager/TA-dmarc/apps/local/TA-dmarc/setup?action=edit
if i change the url to https://10.4.100.1/en-GB/app/TA-dmarc it shows the app config page

App configuration
The "TA-dmarc" app has not been fully configured yet.

This app has configuration properties that can be customized for this Splunk instance. Depending on the app, these properties may or may not be required.

continue to app setup page gives out the error "The server encountered an unexpected condition which prevented it from fulfilling the request. Click here to return to Splunk homepage."

given below is the request id search results

2021-06-30 17:19:08,873 ERROR	[60dc5a33921ab76cbc8c8] error:335 - Traceback (most recent call last):
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\cherrypy\_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\cherrypy\_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\htmlinjectiontoolfactory.py", line 75, in wrapper
    resp = handler(*args, **kwargs)
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\routes.py", line 383, in default
    return route.target(self, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-486&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 40, in rundecs
    return fn(*a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-484&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 118, in check
    return fn(self, *a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-483&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 166, in validate_ip
    return fn(self, *a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-482&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 245, in preform_sso_check
    return fn(self, *a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-481&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 284, in check_login
    return fn(self, *a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-480&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 304, in handle_exceptions
    return fn(self, *a, **kw)
  File "&lt;C:\Program Files\Splunk\Python-3.7\lib\site-packages\decorator.py:decorator-gen-475&gt;", line 2, in listEntities
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\lib\decorators.py", line 359, in apply_cache_headers
    response = fn(self, *a, **kw)
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\appserver\mrsparkle\controllers\admin.py", line 1739, in listEntities
    app_name = eai_acl.get('app')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tonyjoseph-sfo** [comment]
can this be fixed ?

**Comment by aholzel** [comment]
I will have a look at it, but I honestly have never tried Splunk on Windows 10. I theory everything should work... but he that is theorie..  what version of Splunk are you running?

**Comment by tonyjoseph-sfo** [comment]
splunk, the latest one 8.2, my other apps are working only this one is having issue.
